[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "paris"  # Important for Base compatibility

# For Base mainnet
[rpc_endpoints]
base = "${BASE_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }

# Default network when you run `forge script`
[profile.default.networks.base]
chain_id = 8453
gas_price = 1000000000  # 1 gwei
priority_fee = 100000000  # 0.1 gwei

# These settings make verification work correctly on Base
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false